import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} mt-4`}>
        <nav>
          <ul className="flex gap-4 justify-center">
            <li>
              <Link href="/tokens"> Lending Tokens</Link>
            </li>
            <li>
              <Link href="credit">Get/Lend Credit</Link>
            </li>
            <li>
              <Link href="swap">Visit Swap</Link>
            </li>
            <li>
              <Link href="liquidity">Manage Liquidity</Link>
            </li>
          </ul>
        </nav>
        {children}
        <footer className="flex justify-center mb-0 mt-[6rem]">
          Copyrights &copy; 2023
        </footer>
      </body>
    </html>
  );
}
